### ISSUE TITLE
high peak density sites and high-frequency SD chi-square test

### ISSUE THREAD

**Issue by rmflight** [MoseleyBioinformaticsLab/manuscript.peakCharacterization#9]
I created a modified version of the high-peak-density detector that works in frequency space, and converted the xcalibur peak lists to frequency space.

Then I can find our own peaks that would have been part of HPD sites using the ranges from the HPD detector.

I also have the peaks that we decided had unusually *high* standard deviations (HighSD) from the underlying frequency level peaks.

It is trivial to find the peaks that are *either* HPD or HighSD, and generate a contingency table of them. 

```
              HPD
HighSD  FALSE TRUE
  FALSE     0   29
  TRUE     58   49
```

Of course, with a contingency table, we can easily do a Chi-square test. 
In this case, we get a really significant p-value:

```
	Pearson's Chi-squared test with Yates'
	continuity correction
data:  cont_table
X-squared = 25.237, 
df = 1, 
p-value = 5.069e-07
```

@hunter-moseley, does this make sense as a way to evaluate the overlap of the HighSD and HPD? We can plot them as well obviously.

**Comment by hunter-moseley** [comment]
Throw these results into supplemental material.

We can talk about them in the main text.
